# Generated by Django 6.0.3 on 2026-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField()),
                ('userContact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('bookName', models.CharField(max_length=50)),
                ('author', models.CharField()),
                ('quantity', models.IntegerField()),
                ('bookPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('paymentType', models.CharField()),
            ],
        ),
    ]
